### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by mat-sz** [mat-sz/filedrop#23]
Making this issue just to track the potential problems from the migration to monorepo/vite.

Also:

@rehanone I've changed a lot in the repository, could you check if the Docker image still builds/works as expected? Note that the env variable names have been changed too.

**Comment by rehanone** [comment]
@mat-sz , thanks for the heads up. Will check!

**Comment by rehanone** [comment]
@mat-sz , Sorry for a very late replay to this thread. I finally did manage to get around created new docker images based on new codebase as the two version are now combined in one. I had not seen any issues using the image and it worked without issue.

The new image is available here [rehanone/filedrop](https://hub.docker.com/r/rehanone/filedrop) if anyone want to use them in systems other than Docker; like Kubernetes for example and want to pull a pre-build image. 

I have noticed on thing though, the new image size has almost doubled and also the memory usage is gone up considerably. I think it is because the build tooling for npm is still part of the image. Maybe it would make sense to use a layered build and deploy sections in Dockerfile.

Once again thanks for the great refactoring work to simplify the codebase!
