### ISSUE TITLE
question

### ISSUE THREAD

**Issue by chieve-bale** [mat-sz/filedrop#27]
this is a really helpful tool.
but i wann know does it necessary to use the node.js to run ws code on my webserver.
my web server really poor of raw and cpu(a vps only has 200m raw and one core cpu ), 
so are there any way i can build filedrop's web and ws as static files , so that i can place it in my vps and use nginx to proxy the file, and run js on client   browsers. so that i can save a lot of raw to run others services.
forgive me as a freshman putting this question，thanks a lot.

**Comment by mat-sz** [comment]
@chieve-bale

Hello,

You could take a look at the old configuration file that was used before: https://github.com/mat-sz/filedrop-docker/blob/4e5dd1c28495d0c707da78bf6db15a7de5e5c312/conf/nginx/nginx.conf
Building the app is possible with `yarn build`, although you would have to remove the static file serving code from the `ws` project.

Unfortunately, since your use case is too niche and out of scope of the project, I can't add this due to the maintenance cost.
